# Default initial positions for ur's ros2_control fake system

initial_positions:
  shoulder_pan_joint: 1.57
  shoulder_lift_joint: -2.0944
  elbow_joint: 1.57
  wrist_1_joint: 0.523599
  wrist_2_joint: 1.57
  wrist_3_joint: 3.14
  robotiq_85_left_knuckle_joint: 0.8