<?xml version="1.0"?>

<!--
// Copyright 2022 Stereolabs
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<robot name="stereolabs_camera" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="camera_name"   default="zed" />
  <xacro:arg name="camera_model"  default="zed" />
  <xacro:arg name="base_frame"    default="flange" />
  <xacro:arg name="cam_pos_x"     default="0.02" />
  <xacro:arg name="cam_pos_y"     default="0" />
  <xacro:arg name="cam_pos_z"     default="0.035" />
  <xacro:arg name="cam_roll"      default="0" />
  <xacro:arg name="cam_pitch"     default="0" />
  <xacro:arg name="cam_yaw"       default="0" />
  <xacro:arg name="gnss_frame"    default="" />

  <xacro:include filename="$(find ur_description)/urdf/materials.urdf.xacro" />
  <xacro:property name="M_PI"     value="3.1415926535897931" />
  <xacro:macro name="zed_camera" params="name=zed model=zed parent *origin">
    <xacro:if value="${model == 'zed'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedm'}">
      <xacro:property name="baseline" value="0.06" />
      <xacro:property name="height" value="0.0265" />
      <xacro:property name="bottom_slope" value="0.0" /> 
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="0.0" />
    </xacro:if>
    <xacro:if value="${model == 'zed2'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zed2i'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="-0.01" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedx'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.032" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.016" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>
    <xacro:if value="${model == 'zedxm'}">
      <xacro:property name="baseline" value="0.05" />
      <xacro:property name="height" value="0.032" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.016" />
      <xacro:property name="optical_offset_x" value="-0.01" />
    </xacro:if>

    <!-- Camera mounting point (the threaded screw hole in the bottom) -->
    <link name="${name}_base_link" />
    <joint name="${name}_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}_base_link"/>
      <xacro:insert_block name="origin" />
    </joint>

    <link name="${name}_link_optical" />
    <joint name="${name}_optical_joint" type="fixed">
        <parent link="${name}_base_link"/>
        <child link="${name}_link_optical"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Camera Center -->
    <link name="${name}_camera_center">
      <visual>
        <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://ur_description/urdf/meshes/${model}.stl" />
        </geometry>
        <material name="${model}_mat" />
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur_description/urdf/meshes/${model}.stl" />
        </geometry>
      </collision>
    </link>
    <joint name="${name}_camera_center_joint" type="fixed">
      <parent link="${name}_base_link"/>
      <child link="${name}_camera_center"/>
      <origin xyz="0 0 ${height/2}" rpy="0 ${bottom_slope} 0" />
    </joint>

    <!-- Left Camera -->
    <link name="${name}_left_camera_frame" />
    <joint name="${name}_left_camera_joint" type="fixed">
      <parent link="${name}_camera_center"/>
      <child link="${name}_left_camera_frame"/>
      <origin xyz="${optical_offset_x} ${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_left_camera_optical_frame"/>
    <joint name="${name}_left_camera_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
      <parent link="${name}_left_camera_frame"/>
      <child link="${name}_left_camera_optical_frame"/>
    </joint>

    <!-- Right Camera -->
    <link name="${name}_right_camera_frame" />
    <joint name="${name}_right_camera_joint" type="fixed">
      <parent link="${name}_camera_center"/>
      <child link="${name}_right_camera_frame"/>
      <origin xyz="${optical_offset_x} -${baseline/2} 0" rpy="0 0 0" />
    </joint>

    <link name="${name}_right_camera_optical_frame"/>
    <joint name="${name}_right_camera_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
      <parent link="${name}_right_camera_frame"/>
      <child link="${name}_right_camera_optical_frame"/>
    </joint>

    <!-- ZED2 Sensors -->
    <xacro:if value="${model == 'zed2'}">
      <link name="${name}_mag_link" />
      <joint name="${name}_mag_joint" type="fixed">
        <parent link="${name}_camera_center"/>
        <child link="${name}_mag_link"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>

      <link name="${name}_baro_link" />
      <joint name="${name}_baro_joint" type="fixed">
        <parent link="${name}_camera_center"/>
        <child link="${name}_baro_link"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>

      <link name="${name}_temp_left_link" />
      <joint name="${name}_temp_left_joint" type="fixed">
        <parent link="${name}_left_camera_frame"/>
        <child link="${name}_temp_left_link"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>

      <link name="${name}_temp_right_link" />
      <joint name="${name}_temp_right_joint" type="fixed">
        <parent link="${name}_right_camera_frame"/>
        <child link="${name}_temp_right_link"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </joint>
    </xacro:if>
  </xacro:macro>

  <xacro:zed_camera name="$(arg camera_name)" model="$(arg camera_model)" parent="$(arg base_frame)">
    <origin 
      xyz="$(arg cam_pos_x) $(arg cam_pos_y) $(arg cam_pos_z)" 
      rpy="$(arg cam_roll) $(arg cam_pitch) $(arg cam_yaw)"
    />
  </xacro:zed_camera>

  <gazebo reference="$(arg camera_name)_base_link">
    <sensor name="$(arg camera_name)_sensor" type="depth">
      <update_rate>20</update_rate>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047198</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>3</far>
        </clip>
      </camera>
      <plugin name="$(arg camera_name)_controller" filename="libgazebo_ros_camera.so">
        <baseline>0.2</baseline>
        <alwaysOn>false</alwaysOn>
        <updateRate>1.0</updateRate>
        <cameraName>$(arg camera_name)_ir</cameraName>
        <imageTopicName>/$(arg camera_name)/color/image_raw</imageTopicName>
        <cameraInfoTopicName>/$(arg camera_name)/color/camera_info</cameraInfoTopicName>
        <depthImageTopicName>/$(arg camera_name)/depth/image_raw</depthImageTopicName>
        <depthImageInfoTopicName>/$(arg camera_name)/depth/camera_info</depthImageInfoTopicName>
        <pointCloudTopicName>/$(arg camera_name)/depth/points</pointCloudTopicName>
        <frameName>$(arg camera_name)_link_optical</frameName>
        <pointCloudCutoff>0.5</pointCloudCutoff>
        <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
        <distortionK1>0.00000001</distortionK1>
        <distortionK2>0.00000001</distortionK2>
        <distortionK3>0.00000001</distortionK3>
        <distortionT1>0.00000001</distortionT1>
        <distortionT2>0.00000001</distortionT2>
        <CxPrime>0</CxPrime>
        <Cx>0</Cx>
        <Cy>0</Cy>
        <focalLength>0</focalLength>
        <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>

</robot>
